"""initial schema

Revision ID: 503814064d2b
Revises:
Create Date: 2026-09-03 20:18:04.989783

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "503814064d2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("errors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_errors_component"), ["component"], unique=False)
        batch_op.create_index(batch_op.f("ix_errors_ts"), ["ts"], unique=False)

    op.create_table(
        "markets",
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("event_ticker", sa.String(length=64), nullable=True),
        sa.Column("series_ticker", sa.String(length=64), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subtitle", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiration_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.String(length=8), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    with op.batch_alter_table("markets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_markets_event_ticker"), ["event_ticker"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_markets_series_ticker"), ["series_ticker"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_markets_status"), ["status"], unique=False)

    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=True),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=4), nullable=False),
        sa.Column("side", sa.String(length=3), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("filled_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trading_mode", sa.String(length=8), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("order_id"),
        sa.UniqueConstraint("client_order_id", name="uq_orders_client_order_id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_ticker"), ["ticker"], unique=False)

    op.create_table(
        "pnl_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trading_mode", sa.String(length=8), nullable=False),
        sa.Column("cash_cents", sa.Integer(), nullable=False),
        sa.Column("exposure_cents", sa.Integer(), nullable=False),
        sa.Column("realized_pnl_cents", sa.Integer(), nullable=False),
        sa.Column("unrealized_pnl_cents", sa.Integer(), nullable=False),
        sa.Column("fees_cents", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pnl_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pnl_snapshots_trading_mode"), ["trading_mode"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pnl_snapshots_ts"), ["ts"], unique=False)

    op.create_table(
        "positions",
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("trading_mode", sa.String(length=8), nullable=False),
        sa.Column("yes_contracts", sa.Integer(), nullable=False),
        sa.Column("no_contracts", sa.Integer(), nullable=False),
        sa.Column("avg_yes_cost", sa.Float(), nullable=False),
        sa.Column("avg_no_cost", sa.Float(), nullable=False),
        sa.Column("realized_pnl_cents", sa.Integer(), nullable=False),
        sa.Column("fees_cents", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "trading_mode"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=3), nullable=False),
        sa.Column("model_probability", sa.Float(), nullable=False),
        sa.Column("market_probability", sa.Float(), nullable=False),
        sa.Column("edge", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("limit_price", sa.Integer(), nullable=False),
        sa.Column("suggested_contracts", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signals_strategy"), ["strategy"], unique=False)
        batch_op.create_index(batch_op.f("ix_signals_ticker"), ["ticker"], unique=False)
        batch_op.create_index("ix_signals_ticker_ts", ["ticker", "ts"], unique=False)

    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_strategy_name_version"),
    )
    op.create_table(
        "agent_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("risk_checks", sa.JSON(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("trading_mode", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_decisions_decision"), ["decision"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_decisions_ticker"), ["ticker"], unique=False)

    op.create_table(
        "fills",
        sa.Column("fill_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=4), nullable=False),
        sa.Column("side", sa.String(length=3), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("fee_cents", sa.Integer(), nullable=False),
        sa.Column("is_taker", sa.Boolean(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.order_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("fill_id"),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fills_ticker"), ["ticker"], unique=False)

    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=64), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("yes_bid", sa.Integer(), nullable=True),
        sa.Column("yes_ask", sa.Integer(), nullable=True),
        sa.Column("no_bid", sa.Integer(), nullable=True),
        sa.Column("no_ask", sa.Integer(), nullable=True),
        sa.Column("last_price", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("open_interest", sa.Integer(), nullable=False),
        sa.Column("yes_depth", sa.Integer(), nullable=True),
        sa.Column("no_depth", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["ticker"], ["markets.ticker"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_snapshots_ticker_ts", ["ticker", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_snapshots_ticker_ts")

    op.drop_table("market_snapshots")
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fills_ticker"))

    op.drop_table("fills")
    with op.batch_alter_table("agent_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_decisions_ticker"))
        batch_op.drop_index(batch_op.f("ix_agent_decisions_decision"))

    op.drop_table("agent_decisions")
    op.drop_table("strategy_versions")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_ticker_ts")
        batch_op.drop_index(batch_op.f("ix_signals_ticker"))
        batch_op.drop_index(batch_op.f("ix_signals_strategy"))

    op.drop_table("signals")
    op.drop_table("positions")
    with op.batch_alter_table("pnl_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pnl_snapshots_ts"))
        batch_op.drop_index(batch_op.f("ix_pnl_snapshots_trading_mode"))

    op.drop_table("pnl_snapshots")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_ticker"))
        batch_op.drop_index(batch_op.f("ix_orders_status"))

    op.drop_table("orders")
    with op.batch_alter_table("markets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_markets_status"))
        batch_op.drop_index(batch_op.f("ix_markets_series_ticker"))
        batch_op.drop_index(batch_op.f("ix_markets_event_ticker"))

    op.drop_table("markets")
    with op.batch_alter_table("errors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_errors_ts"))
        batch_op.drop_index(batch_op.f("ix_errors_component"))

    op.drop_table("errors")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
